package org.valkyrienskies.core.game.ships

import org.joml.primitives.AABBd
import org.joml.primitives.AABBdc
import org.valkyrienskies.core.networking.delta.JsonDiffDeltaAlgorithm
import org.valkyrienskies.core.util.serialization.VSJacksonUtil

/**
 * A [ShipObject] is essentially a [ShipData] that has been loaded.
 *
 * Its just is to interact with the player. This includes stuff like rendering, colliding with entities, and adding
 * a rigid body to the physics engine.
 */
open class ShipObject(
    shipData: ShipDataCommon
) {
    @Suppress("CanBePrimaryConstructorProperty") // don't want to refer to open val in constructor
    open val shipData: ShipDataCommon = shipData

    // Used for debug rendering to see AABBs generated by Krunch
    // TODO: Send this to the client through networking
    var debugShipPhysicsAABB: AABBdc = AABBd()

    companion object {
        @JvmStatic
        protected val jsonDiffDeltaAlgorithm = JsonDiffDeltaAlgorithm(VSJacksonUtil.deltaMapper)
    }
}
